ALTER TABLE pay_emp_trn_salary
CHANGE COLUMN created_date_time created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
CHANGE COLUMN updated_date_time updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP;