ALTER TABLE pay_mst_ps_emp
CHANGE COLUMN create_date created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
CHANGE COLUMN create_by created_by VARCHAR(50) NOT NULL DEFAULT '',
CHANGE COLUMN update_date updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
CHANGE COLUMN update_by updated_by VARCHAR(50) DEFAULT NULL;